company_sendmail:
    pattern:  /sendmail
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:sendMail" }
    requirements: { _method: post|put }

company_list:
    pattern:  /list
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:list" }

company:
    pattern:  /
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:index" }

company_show:
    pattern:  /{id}/show
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:show" }

company_new:
    pattern:  /new
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:new" }

company_create:
    pattern:  /create
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:create" }
    requirements: { _method: post }

company_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:edit" }

company_update:
    pattern:  /{id}/update
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:update" }
    requirements: { _method: post|put }

company_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DevsparkVentureJuiceBundle:Company:delete" }
    requirements: { _method: post|delete }
