<?php

namespace Devspark\VentureJuiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailMessageRepository extends EntityRepository
{
   public function findDefaultMessage()
    {
        $repository = $this->getEntityManager()->getRepository('DevsparkVentureJuiceBundle:EmailMessage');

        $query = $repository->createQueryBuilder('e')
            ->where('e.company IS NULL')
            ->getQuery();
        $emailMessage = $query->getOneOrNullResult();

        return $emailMessage;

    }

   public function findCompanyMessage($company)
    {
        $repository = $this->getEntityManager()->getRepository('DevsparkVentureJuiceBundle:EmailMessage');

        $query = $repository->createQueryBuilder('e')
            ->where('e.company = :companyId')
            ->setParameter('companyId', $company->getId())
            ->getQuery();
        $emailMessage = $query->getOneOrNullResult();

        return $emailMessage;

    }

   public function test($data) {
       var_dump("llega");
       exit;
   }
}
